/** @file
**/

#ifndef __AMD_APCB_DXE_H__
#define __AMD_APCB_DXE_H__


#define AMD_APCB_DXE_PROTOCOL_GUID { 0x7189E04E,0x6284,0x4953,{ 0xA5,0x43,0xA3,0x1F,0x89,0xA1,0xA7,0xBF } }

typedef struct _AMD_APCB_DXE_PROTOCOL AMD_APCB_DXE_PROTOCOL;

typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_1)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_2)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, uint32_t* arg3);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_3)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_4)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_5)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_6)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_7)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_8)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_9)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_10)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_11)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_12)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_13)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_14)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_15)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_16)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_17)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_18)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_19)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_20)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_21)(AMD_APCB_DXE_PROTOCOL* This, int32_t* arg2, int32_t arg3, int32_t arg4);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_22)(AMD_APCB_DXE_PROTOCOL* This, char* arg2, int16_t arg3, int16_t arg4, int16_t arg5, void** arg6, int32_t* arg7);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_23)(AMD_APCB_DXE_PROTOCOL* This, char* arg2, int16_t arg3, int16_t arg4, int16_t arg5, void** arg6, int32_t* arg7);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_24)(AMD_APCB_DXE_PROTOCOL* This, char arg2);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_25)(AMD_APCB_DXE_PROTOCOL* This, char arg2);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_26)(AMD_APCB_DXE_PROTOCOL* This, char arg2);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_27)(AMD_APCB_DXE_PROTOCOL* This, char arg2);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_28)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_29)(AMD_APCB_DXE_PROTOCOL* This);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_30)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_31)(AMD_APCB_DXE_PROTOCOL* This);
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_32)();
typedef EFI_STATUS (* AMD_APCB_DXE_FUNCTION_33)(AMD_APCB_DXE_PROTOCOL* This);

struct _AMD_APCB_DXE_PROTOCOL __packed
{
	UINTN Version;
	AMD_APCB_DXE_FUNCTION_1 Function1;
	AMD_APCB_DXE_FUNCTION_2 Function2;
	AMD_APCB_DXE_FUNCTION_3 Function3;
	AMD_APCB_DXE_FUNCTION_4 Function4;
	AMD_APCB_DXE_FUNCTION_5 Function5;
	AMD_APCB_DXE_FUNCTION_6 Function6;
	AMD_APCB_DXE_FUNCTION_7 Function7;
	AMD_APCB_DXE_FUNCTION_8 Function8;
	AMD_APCB_DXE_FUNCTION_9 Function9;
	AMD_APCB_DXE_FUNCTION_10 Function10;
	AMD_APCB_DXE_FUNCTION_11 Function11;
	AMD_APCB_DXE_FUNCTION_12 Function12;
	AMD_APCB_DXE_FUNCTION_13 PostPgoInitialization;
	AMD_APCB_DXE_FUNCTION_14 Function14;
	AMD_APCB_DXE_FUNCTION_15 Function15;
	AMD_APCB_DXE_FUNCTION_16 Function16;
	AMD_APCB_DXE_FUNCTION_17 Function17;
	AMD_APCB_DXE_FUNCTION_18 Function18;
	AMD_APCB_DXE_FUNCTION_19 Function19;
	AMD_APCB_DXE_FUNCTION_20 Function20;
	AMD_APCB_DXE_FUNCTION_21 Function21;
	AMD_APCB_DXE_FUNCTION_22 Function22;
	AMD_APCB_DXE_FUNCTION_23 Function23;
	AMD_APCB_DXE_FUNCTION_24 Function24;
	AMD_APCB_DXE_FUNCTION_25 Function25;
	UINTN Unknown1;
	AMD_APCB_DXE_FUNCTION_26 Function26;
	AMD_APCB_DXE_FUNCTION_27 Function27;
	EFI_GUID Guid1;
	UINTN Unknown2;
	EFI_GUID Guid2;
	UINTN Unknown3;
	EFI_GUID Guid3;
    UINT8 Unknown4[80];
	AMD_APCB_DXE_FUNCTION_28 Function28;
	AMD_APCB_DXE_FUNCTION_29 Function29;
    UINT8 Unknown5[40];
	AMD_APCB_DXE_FUNCTION_30 Function30;
	AMD_APCB_DXE_FUNCTION_31 Function31;
    UINT8 Unknown6[40];
	AMD_APCB_DXE_FUNCTION_32 Function32;
	AMD_APCB_DXE_FUNCTION_33 Function33;
    UINT8 Unknown7[16];
};

extern EFI_GUID  gAmdApcbDxeProtocolGuid;

#endif